server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/vot?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    username: root
    password: 821827aa
    druid:
      initial-size: 5 #连接池初始化大小
      min-idle: 10 #最小空闲连接数
      max-active: 20 #最大连接数
      max-wait: 60000
## 记载静态资源需要
  web:
    resources:
      static-locations: classpath:/

mybatis:
  mapper-locations:
    - classpath:mapper/*.xml

